plugins {
    id "java"
}

group = rootProject.maven_group
version = rootProject.mod_version
base.archivesName = project.archives_base_name

repositories {
    mavenCentral()
    maven { url = "https://maven.fabricmc.net/" }
}

dependencies {
    compileOnly "net.fabricmc:fabric-loader:${project.loader_version}"
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand version: project.version
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = "UTF-8"
}
